download_url: https://galaxy.ansible.com/download/awx-awx-23.1.0.tar.gz
format_version: 1.0.0
name: awx
namespace: awx
server: https://galaxy.ansible.com/api/
signatures: []
version: 23.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/awx/awx/versions/23.1.0/
