---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
    #find other image options here: https://catalog.redhat.com/software/containers/ansible-automation-platform/
    #registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9@latest
    #registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8@latest
    
dependencies:
  galaxy:
    collections:
    - name: community.vmware
    - name: infoblox.nios_modules
  python: requirements.txt
  system: bindep.txt

#Uncomment if you are building from the RHEL ubi or minimal ee image
options:
   package_manager_path: /usr/bin/microdnf

#ansible-builder build --tag=my-custom-ee
